[theme]

# Primary accent for interactive elements
primaryColor = '#56BABA'

# Background color for the main content area
backgroundColor = '#FFF3E5'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#A3CCAB'

# Color used for almost all text
textColor = '#14140F'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"